package br.com.zemaromba.core_ui.ui.theme

import androidx.compose.ui.graphics.Color

object DarkMode {
    val Primary = Color(0xFFffb867)
    val OnPrimary = Color(0xFF482900)
    val PrimaryContainer = Color (0xFF673d00)
    val OnPrimaryContainer = Color(0xFFffddba)
    val Secondary = Color (0xFFe0c1a3)
    val OnSecondary = Color(0xFF402d17)
    val SecondaryContainer = Color (0xFF58432c)
    val OnSecondaryContainer = Color(0xFFfdddbd)
    val Tertiary = Color (0xFFbdcd9c)
    val OnTertiary = Color(0xFF283412)
    val TertiaryContainer = Color(0xFF3e4b26)
    val OnTertiaryContainer = Color(0xFFd9e9b7)
    val Error = Color(0xFFffb4ab)
    val OnError = Color(0xFF690005)
    val ErrorContainer = Color(0xFF93000a)
    val OnErrorContainer = Color(0xFFffdad6)
    val Background = Color (0xFF1f1b16)
    val OnBackground = Color(0xFFebe1d9)
    val Surface = Color(0xFF1f1b16)
    val OnSurface = Color(0xFFebe1d9)
    val Outline = Color(0xFF9d8e81)
    val SurfaceVariant = Color(0xFFf1dfd0)
    val OnSurfaceVariant = Color(0xFF50453a)
}

object LightMode {
    val Primary = Color(0xFF875200)
    val OnPrimary = Color(0xFFFFFFFF)
    val PrimaryContainer = Color (0xFFffddba)
    val OnPrimaryContainer = Color(0xFF2b1700)
    val Secondary = Color (0xFF715a41)
    val OnSecondary = Color(0xFFffffff)
    val SecondaryContainer = Color (0xFFfdddbd)
    val OnSecondaryContainer = Color(0xFF281805)
    val Tertiary = Color (0xFF56633c)
    val OnTertiary = Color(0xFFffffff)
    val TertiaryContainer = Color(0xFFd9e9b7)
    val OnTertiaryContainer = Color(0xFF141f01)
    val Error = Color(0xFFba1a1a)
    val OnError = Color(0xFFffffff)
    val ErrorContainer = Color(0xFFffdad6)
    val OnErrorContainer = Color(0xFF410002)
    val Background = Color (0xFFfffbff)
    val OnBackground = Color(0xFF1f1b16)
    val Surface = Color(0xFFfffbff)
    val OnSurface = Color(0xFF1f1b16)
    val Outline = Color(0xFF827568)
    val SurfaceVariant = Color(0xFFf1dfd0)
    val OnSurfaceVariant = Color(0xFF50453a)
}

